config/routes.rb
Rails.application.routes.draw do
  root 'articles#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.all
  end

  def new

  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  private def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/index.html.erb
<html>
<head>

</head>
  <body>
  <h1><em><b>> Статьи</b></em></h1><br/>
    <% @article.each do |article| %>
      <h3><strong><%= article.title %></strong></h3>
      <h6><em><%= article.body %></em></h6><br/>
    <br/>
  <% end %>
  </body>
</html>

app/views/articles/new.html.erb
<h1><em><b>> Добавить статью</b></em></h1><br/>
<br/>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <em>Название статьи:</em><br/>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    <em>Текст статьи:</em><br/>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit 'Добавить статью',({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1><em><b>> <%= @article.title %>  </b></em></h1><br/><h3></h3>
<h5><%= @article.body %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand">W E T I C E</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <span class="nav-link"><%= link_to "Статьи", home_path %></span>
        </li>
        <li class="nav-item">
          <span class="nav-link" ><%= link_to "Добавить", new_article_path %></span>
        </li>
        <li class="nav-item">
          <span class="nav-link" ><%= link_to "О проекте", about_path %></span>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container mt-5">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<html>
<head>
<body>
<h1><em><b>> О проекте</b></em></h1><br/>
<p>
  <small><em>На этой странице, будет отображаться информация о проекте WETICE! :)</em></small>
</p>


</body>
</head>
</html>